version: "3"

services:
  node:
    container_name: node
    build: ./node
    image: mmilholm/node-srv
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./app:/home/node/app
    command: "nodemon -L"
  db:
    image: mongo:3.4.10
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=stubcam
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d    
